# Generated by Django 6.0.3 on 2026-05-14 03:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_event_artists_remove_ticketcategory_event_and_more'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artist',
            table=None,
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('quota', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_categories', to='accounts.event')),
            ],
            options={
                'db_table': 'accounts_ticketcategory',
                'ordering': ['event__event_title', 'category_name'],
            },
        ),
        migrations.CreateModel(
            name='EventArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.artist')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.event')),
            ],
            options={
                'db_table': 'accounts_eventartist',
                'unique_together': {('event', 'artist')},
            },
        ),
    ]
