# Generated by Django 4.2.24 on 2026-05-14 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_ticketcategory_event_remove_event_artists_and_more'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcategory',
            options={'ordering': ['event__event_title', 'category_name']},
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_categories', to='accounts.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='genre',
            field=models.CharField(blank=True, default='Pop', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='artist',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ticketcategory',
            table=None,
        ),
        migrations.CreateModel(
            name='EventArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.artist')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.event')),
            ],
            options={
                'unique_together': {('event', 'artist')},
            },
        ),
    ]
