# Generated by Django 6.0.3 on 2026-05-14 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_artist_table_ticketcategory_eventartist'),
        ('events', '0002_alter_ticketcategory_options_ticketcategory_event_and_more'),
    ]

    operations = [
    ]
