# Generated by Django 4.2.24 on 2026-05-13 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(through='accounts.EventArtist', to='events.artist'),
        ),
        migrations.AlterField(
            model_name='eventartist',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.artist'),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
