# Generated by Django 6.0.3 on 2026-05-14 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_event_artists_alter_eventartist_artist_and_more'),
    ]

    operations = [
    ]
