# Generated by Django 6.0.3 on 2026-05-14 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_event_artists_remove_ticketcategory_event_and_more'),
        ('accounts', '0003_remove_ticketcategory_event_remove_event_artists_and_more'),
    ]

    operations = [
    ]
