# Generated by Django 4.2.24 on 2026-05-14 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ticket_code', models.CharField(max_length=50, unique=True)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='orders.order')),
                ('seat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.seat')),
                ('ticket_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.ticketcategory')),
            ],
        ),
    ]
